# Basic
title: xiaomi
subtitle: ä¸ªäººåšå®¢
description: å°ç±³çš„ä¸ªäººåšå®¢ï¼Œæ¬¢è¿äº¤æµ
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: ç±³æ™ºæ¬
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Java/python/ç®—æ³•
url: "https://mizhitian-xiaomi.github.io"

# Comment
comment:
    disqus: mizhitian
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weibo: å“å“ŸåŸæ¥æ˜¯ç¾å°‘å¥³ 
    github: mizhitian-xiaomi
    # zhihu: panpanleopard
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 
    mail: xiaomi.mzt@qq.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: c55071254a66637b6fe52c323d0fff49 

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#     id: xxxx  
#     host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ‰€æœ‰åˆ†ç±», description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


